server:
  port: 8086
spring:
  application:
    name: spring-boot-server
  datasource:
    url: jdbc:mysql://us-cdbr-east-04.cleardb.com:3306/heroku_4fda505d6c16e6e
    username: bde1df3a09b9c1
    password: 601523a9
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect